#!/usr/bin/env bash
# Build PicoBoot .uf2 images for cubiboot.
#
# PicoBoot (webhdx/PicoBoot) is the RP2040/RP2350 IPL-replacement modchip. It is a
# DIFFERENT product from PicoLoader (makeo), which is what .ci/make_picoloader_uf2.py
# targets -- PicoLoader serves cubiboot.iso to the disc drive interface, PicoBoot
# injects a .dol over EXI in place of the console's BS2. Both are shipped.
#
# Flash layout (PicoBoot memmap_picoboot.ld): firmware occupies 512K at
# 0x10000000, and the payload lives in the remaining 1536K at 0x10080000. The
# payload blob is "IPLBOOT " + BE32 total size + the scrambled, flattened .dol +
# a trailing "PICO" magic. We do not reimplement any of that: the payload is
# generated by PicoBoot's own tools/process_ipl.py, cloned at build time (the
# same approach .ci/build_apploader.sh takes with the swiss-gc packer).
#
# THE PAYLOAD IS entry/entry.dol, NOT cubeboot/cubeboot.dol. PicoBoot replaces
# BS2, so process_ipl.py hard-requires entry point 0x81300000 / load 0x01300000.
# entry.dol is linked exactly there (it is the gzip self-extractor that unpacks
# and runs cubeboot.dol); cubeboot.dol itself is a normal libogc image at
# 0x80003100 and process_ipl.py rejects it outright. The check below fails loudly
# rather than letting a silently-wrong payload get built.
#
# Outputs (into <repo>/dist):
#   cubiboot_picoboot_payload.uf2  payload only, both RP2040+RP2350 families.
#                                  Flash onto a Pico that ALREADY has PicoBoot to
#                                  swap the payload without touching the firmware.
#   cubiboot_picoboot_pico.uf2     full image (PicoBoot firmware + our payload),
#   cubiboot_picoboot_pico2.uf2    for a fresh install. Firmware is taken from the
#                                  official PicoBoot release with its own stock
#                                  payload blocks dropped.
#
# The full images need network access to fetch the PicoBoot release. If it is
# unreachable the payload-only .uf2 is still produced and the script warns rather
# than failing, so an offline build still yields something usable.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PAYLOAD_DOL="${PICOBOOT_PAYLOAD:-$REPO/entry/entry.dol}"
PICOBOOT_GIT="${PICOBOOT_GIT:-https://github.com/webhdx/PicoBoot.git}"
PICOBOOT_REL="${PICOBOOT_REL:-https://github.com/webhdx/PicoBoot/releases/latest/download}"
PAYLOAD_BASE=0x10080000   # must match PicoBoot's memmap_picoboot.ld

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

[ -f "$PAYLOAD_DOL" ] || { echo "ERROR: payload .dol not found at $PAYLOAD_DOL (build entry/ first)" >&2; exit 1; }
mkdir -p "$REPO/dist"

# Reject the wrong .dol before we get a confusing error out of process_ipl.py.
python3 - "$PAYLOAD_DOL" <<'PY'
import struct, sys
d = open(sys.argv[1], "rb").read()
h = struct.unpack(">64I", d[:256])
addr, size = h[18:36], h[36:54]
entry = h[56]
load = min(a for a in addr if a)
hi = max(a + s for a, s in zip(addr, size))
print(">> payload %s: entry=%08X load=%08X..%08X (%d bytes)" % (sys.argv[1], entry, load, hi, hi - load))
if entry != 0x81300000 or (load & 0x017FFFFF) != 0x01300000:
    raise SystemExit("ERROR: PicoBoot payload must be linked at 0x81300000 (this is entry/entry.dol, "
                     "not cubeboot/cubeboot.dol)")
if hi - load > 1536 * 1024:
    raise SystemExit("ERROR: payload image exceeds PicoBoot's 1536K payload region")
PY

# PicoBoot's own tooling: process_ipl.py builds the payload .uf2 (it owns the
# bootrom descrambler), merge_uf2.py joins firmware + payload with sector padding.
git clone --depth 1 --filter=blob:none --sparse -q "$PICOBOOT_GIT" "$WORK/picoboot"
git -C "$WORK/picoboot" sparse-checkout set tools >/dev/null
PROCESS_IPL="$WORK/picoboot/tools/process_ipl.py"
MERGE_UF2="$WORK/picoboot/tools/merge_uf2.py"
[ -f "$PROCESS_IPL" ] && [ -f "$MERGE_UF2" ] || { echo "ERROR: PicoBoot tools not found in checkout" >&2; exit 1; }

# merge_uf2.py uses itertools.pairwise (Python 3.10+) for its overlap assertion;
# the cubiboot-dev image ships Python 3.9. Substitute the equivalent zip form so
# the check still runs rather than dropping it or bumping the base image.
if ! python3 -c 'import itertools; itertools.pairwise' 2>/dev/null; then
    sed -i 's/itertools\.pairwise(blocks)/zip(blocks, blocks[1:])/' "$MERGE_UF2"
    grep -q 'zip(blocks, blocks\[1:\])' "$MERGE_UF2" || { echo "ERROR: failed to patch merge_uf2.py for Python 3.9" >&2; exit 1; }
fi

# Payload .uf2s: universal (both families) for the standalone update, plus one
# per family because merge_uf2.py requires a single family id across all blocks.
python3 "$PROCESS_IPL" "$WORK/payload_universal.uf2" "$PAYLOAD_DOL"
python3 "$PROCESS_IPL" "$WORK/payload_rp2040.uf2"    "$PAYLOAD_DOL" rp2040
python3 "$PROCESS_IPL" "$WORK/payload_rp2350.uf2"    "$PAYLOAD_DOL" rp2350

cp "$WORK/payload_universal.uf2" "$REPO/dist/cubiboot_picoboot_payload.uf2"
echo ">> wrote $REPO/dist/cubiboot_picoboot_payload.uf2 ($(stat -c%s "$REPO/dist/cubiboot_picoboot_payload.uf2") bytes, payload only)"

# Round-trip assertion: pull the payload back out of the .uf2 we just wrote,
# undo the scramble (it is an XOR, so applying it twice is the identity) and
# require it to equal the .dol image byte for byte. Catches a stale, truncated or
# misaligned payload shipping silently.
python3 - "$REPO/dist/cubiboot_picoboot_payload.uf2" "$PAYLOAD_DOL" "$PROCESS_IPL" "$PAYLOAD_BASE" <<'PY'
import importlib.util, struct, sys
uf2, dol, tool, base = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4], 0)
spec = importlib.util.spec_from_file_location("pi", tool)
pi = importlib.util.module_from_spec(spec); spec.loader.exec_module(pi)

_, _, ref = pi.flatten_dol(bytearray(open(dol, "rb").read()))

d = open(uf2, "rb").read()
chunks = {}
for i in range(0, len(d), 512):
    b = d[i:i + 512]
    _, _, _, addr, size, _, _, fam = struct.unpack("<8I", b[:32])
    if addr >= base and fam == 0xE48BFF56:   # one family is enough; both carry the same bytes
        chunks[addr] = b[32:32 + size]
img = b"".join(chunks[a] for a in sorted(chunks))

if img[0:8] != b"IPLBOOT ":
    raise SystemExit("ERROR: payload header magic is not 'IPLBOOT '")
total = struct.unpack(">I", img[8:12])[0]
if img[total - 4:total] != b"PICO":
    raise SystemExit("ERROR: payload trailer magic is not 'PICO'")

body = pi.scramble(bytearray(0x720) + bytearray(img[32:total - 4]))[0x720:]
if bytes(body[:len(ref)]) != bytes(ref):
    raise SystemExit("ERROR: payload does not descramble back to %s" % dol)
print(">> verified: payload round-trips to %s (%d bytes)" % (dol, len(ref)))
PY

# Full images. Take the official release and keep only blocks below the payload
# region -- that strips PicoBoot's own stock payload and leaves the firmware.
build_full() {
    # Separate `local` statements on purpose: bash expands every argument to a
    # single `local` before performing any of the assignments, so referring to
    # ${board} in the same statement that declares it is unbound under `set -u`.
    local board="$1"
    local family="$2"
    local out="$REPO/dist/cubiboot_picoboot_${board}.uf2"

    if ! curl -fsSL -o "$WORK/official_${board}.uf2" "$PICOBOOT_REL/picoboot_full_${board}.uf2"; then
        echo "WARNING: could not fetch picoboot_full_${board}.uf2; skipping $out" >&2
        return 0
    fi

    python3 - "$WORK/official_${board}.uf2" "$WORK/fw_${board}.uf2" "$PAYLOAD_BASE" <<'PY'
import struct, sys
src, dst, base = sys.argv[1], sys.argv[2], int(sys.argv[3], 0)
data = open(src, "rb").read()
kept = bytearray()
n = fw = 0
for i in range(0, len(data), 512):
    b = data[i:i + 512]
    m0, m1, flags, addr, size, seq, total, fam = struct.unpack("<8I", b[:32])
    assert m0 == 0x0A324655 and m1 == 0x9E5D5157, "bad UF2 magic in %s" % src
    n += 1
    if addr < base:          # firmware; anything at/above base is its stock payload
        kept += b
        fw += 1
open(dst, "wb").write(bytes(kept))
print(">> %s: %d blocks -> %d firmware blocks (dropped %d stock payload)" % (src.split("/")[-1], n, fw, n - fw))
PY

    python3 "$MERGE_UF2" "$out" "$WORK/fw_${board}.uf2" "$WORK/payload_${family}.uf2"
    echo ">> wrote $out ($(stat -c%s "$out") bytes, firmware + cubiboot payload)"
}

build_full pico  rp2040
build_full pico2 rp2350
